Add asterisk to validation group
codaxy/cxjs pull request #1079
Opened 2023-06-06 14:35 UTC by vedranvucic77

2023-06-06 14:39 UTC, vedranvucic77 commented
fixes #1078

2023-06-07 06:37 UTC, mstijak requested changes
I think this whole logic should have been implemented on the Label component and not on the Field.

2023-06-07 06:39 UTC, mstijak commented on packages/cx/src/widgets/form/Field.js
> +
This part is problematic because the label is a widget, not an instance.

2023-06-07 09:38 UTC, mstijak commented on packages/cx/src/widgets/form/Label.js
> +      if (instance.cache("disabled", data.disabled)) {
If the value obtained from context changes, the label will not re-render. You can fix that with:

if (instance.cache("disabled", data.disabled) || instance.cache("asterisk", data.asterisk))

2023-06-07 09:38 UTC, mstijak approved these changes

2023-06-07 11:11 UTC, merged